FROM python:3.11.2-alpine

WORKDIR /usr/src/app
COPY fastapi .
COPY docker/entrypoint.fastapi.sh /bin/entrypoint.sh

RUN pip install "fastapi[all]" sqlalchemy psycopg2-binary aiohttp

ENTRYPOINT [ "/bin/entrypoint.sh" ]